### ISSUE TITLE
特別碼提示功能無效

### ISSUE THREAD

**Issue by idhowardgj94** [jrywu/DIME#1]
你好，我最近使用了最新的dime行列，發現特別碼提示的功能似乎失效了？
反查功能正常，但是無法提示特別碼。

因為想要搭配快打模式練習特別碼，所以希望可以回覆這項功能

**Comment by jrywu** [comment]
你好，特別碼提示功能已經修復完成，再麻煩下載新的安裝包測試看看。

**Comment by idhowardgj94** [comment]
似乎還是不行耶…我是用windows 10，不知道會不會是相容性的問題？
謝謝修復！
另外想問一下，為什麼後來停止了對大易的支援？聽說已前有

**Comment by jrywu** [comment]
我的測試環境也是 Windows 10 x64，是正常的(如截圖)。請問是完全沒顯示還是顯示錯誤? 
可以的話方便截圖嗎? 
![specialcode](https://cloud.githubusercontent.com/assets/700992/12513933/886aa73e-c15b-11e5-9398-4c8ca4395abc.png)
大易在得到王贊傑先生同意前暫時不會開放

**Comment by idhowardgj94** [comment]
你好：
感謝回復。
看到你的截圖後，我又回去試了一下，發現問題了

首先是特別碼跟反查功能不能同時開啟，否則只會顯示反查字根
在來是關閉反查功能後，一定要開啟聯想字詞功能（如你的圖），
否則特別碼不會出現。

因為沒有特別需要截圖說明的部分，所以我就沒有截圖了，
你可以試試看關掉聯想字詞功能後，特別碼是否還會顯示？

謝謝

**Comment by idhowardgj94** [comment]
啊…還有，
開啟快打模式後，
如果有簡碼，打一般碼會出現錯誤組字的提示 ，
但不會出現特別碼提示，
這部分有辦法修正嗎？

謝謝！

**Comment by jrywu** [comment]
兩個問題都好了，再麻煩測試看看

**Comment by idhowardgj94** [comment]
你好，測試結果都ok，沒有問題了，謝謝！
