### ISSUE TITLE
請教操作問題--直接進入設定畫面

### ISSUE THREAD

**Issue by casinero** [jrywu/DIME#10]
不是反映bug，而是想請教大大
「DIME 大易輸入法設定」這個畫面
可以透過執行什麼.exe檔或command line指令直接呼叫出來嗎
因為Win10只要一有update，做過的設定就會被重設回預設值
然後要經過Win10的好多層畫面點選才能輾轉進到這個畫面進行設定
每隔幾個禮拜就得重覆這動作一次
如果有command line指令可以直接進入，那寫成批次檔放在桌面，就不會那麼麻煩

或是如果有方法讓作業系統更新後輸入法的設定不會被重設當然就更好了

**Comment by jrywu** [comment]
Ctrl-\ 就人叫出來囉!

**Comment by casinero** [comment]
感謝指點!
