### ISSUE TITLE
當切換到DIME行列時，DIME傳統注音輸入法無法設定反查字根為DIME行列

### ISSUE THREAD

**Issue by Shiaobin** [jrywu/DIME#11]
如果目前切換到的輸入法是DIME行列，在DIME傳統注音輸入法設定裡面，反查輸入字根的地方，會沒有DIME行列可選。
![2018-04-18_16-52-38](https://user-images.githubusercontent.com/1549934/38921837-486a7752-4329-11e8-846a-61d8c3e6c60d.png)

不過如果切換到其他輸入法，這時DIME傳統注音輸入法設定裡面，反查輸入字根的地方，就可以選DIME行列了。
![2018-04-18_16-54-10](https://user-images.githubusercontent.com/1549934/38921848-4f23523a-4329-11e8-9260-132764c34b51.png)

作業系統：Windows 10 專業版 64 位元
DIME版本：v1.1.258.21023

**Comment by Shiaobin** [comment]
剛剛更新到v1.1.259.30408，發現還是有相同問題。
![2018-04-18_22-02-08](https://user-images.githubusercontent.com/1549934/38936891-66cd0bd0-4354-11e8-9726-fd4871a14c02.png)

**Comment by jrywu** [comment]
DIME 下的各輸入法在 Windows 下都是獨立註冊的輸入法，各自的設定視窗也都是各自獨立屬於各自輸入法的。輸入法不能查自己，要在注音查行列就是要先切到注音設定查行列，要在行列查注音就是要先切到行列設定查注音。
