### ISSUE TITLE
新增取消英文切換的選項

### ISSUE THREAD

**Issue by mitliao** [jrywu/DIME#12]
目前輸入法可以直接使用 shift 切換中英模式，在某些應用程式視窗中還會被強制切換成英文模式，每次都還要手動切換回來。所以不知道可不可以新增一個選項是可以完全關閉英文輸入？也就是說使用此輸入法時永遠只能輸入中文。

**Comment by jrywu** [comment]
Windows 7 以前這個想法可行，英文輸入是切到另一個輸入法。Windows 8 之後的TSF 架構，輸入英文是每個輸入法自己處理，實質上沒有離開輸入法 (即使按  ctrl-space ) 也一樣 。所以這個想法不可行哦。
