### ISSUE TITLE
請問要如何開啟輸入法設定的頁面？

### ISSUE THREAD

**Issue by mitliao** [jrywu/DIME#13]
可能是 Windows 更新的關係，我忽然找不到可以打開 DIME 輸入法設定頁面的方法了... 這是正常的嗎？
目前的 Windows 版號是 Windows 10 Pro (1803). OS build: 17134.48

**Comment by jrywu** [comment]
Windows 1803 更新後，取消控制台的輸入法頁面。目前唯一進入設定頁面的方法是在一般應用程式  (非 metro apps) 按  ctrl-\ (ctrl 鍵+ 反斜線) 熱鍵 。
