### ISSUE TITLE
Windows 10 - 1803版無法從系統輸入法設定中叫出DIME的設定選單

### ISSUE THREAD

**Issue by gdfan777** [jrywu/DIME#14]
由於 windows 10 1803 版將原本在「控制台」的語言輸入法設定改到windows的「設定 App」中，而在「開始功能表」->左方小齒輪->「時間與語言」->「地區與語言」->「台灣」->「選項」->DIME   這裡沒有「選項」的功能，所以無法叫出DIME輸入法的設定選單。

沒有看到其他可以叫出 DIME 設定選單的方式。只能按組合鍵 CTRL + \  叫出設定選單

**Comment by jrywu** [comment]
感謝您的說明。
沒錯，微軟取消過去在 control panel 的設定進入點，但是新的 metro 介面設定沒有公開第三方輸入法的設定頁面進入API。所以目前唯一進入設定頁面方法是在非 metro apps 按 ctrl + \ 叫出設定選單 。
