### ISSUE TITLE
是否能增加自訂[切換輸入模式(中/英)]按鍵的設定

### ISSUE THREAD

**Issue by chan910ren** [jrywu/DIME#15]
因為Win10透過Shift切換輸入模式(中/英)
使用行列在中英混合輸入的狀況下非常容易誤觸
是否能在DIME行列中增加自訂[切換輸入模式(中/英)]按鍵的設定
例如微軟注音提供使用左側Shift鍵/使用右例Shift鍵的設定
可設定切換輸入模式、確認游標前文字、無
![10](https://user-images.githubusercontent.com/8418672/42072359-ab3527aa-7b92-11e8-94b3-3b6962e3379b.png)

**Comment by jrywu** [comment]
此功能已大致完成，請問願意在 release 前幫忙先測試嗎?

**Comment by chan910ren** [comment]
當然願意，再麻煩跟我說明如何取得測試版本，謝謝

**Comment by mitliao** [comment]
@chan910ren 使用這個安裝檔就可以了: https://github.com/jrywu/DIME/blob/master/installer/DIME-x8664.zip

**Comment by chan910ren** [comment]
已測試左右Shift、左Shift、右Shift及無(僅Ctrl-Space鍵)皆可正常運作
謝謝!!!
