### ISSUE TITLE
請問自建的輸入法的選字鍵能改回傳統大易選字方式嗎?

### ISSUE THREAD

**Issue by C-zerone** [jrywu/DIME#16]
謝謝作者您開發如此方便且支援TSF格式的大易輸入法

有幾件事想要請教?
1.自建的輸入法的選字鍵能改回傳統大易選字方式嗎?
由於自建輸入法導入詞庫cin檔後,雖然可以使用自訂詞組，但是無法使用傳統大易選字方式，只能用數字鍵選字
2.在DIME內建的大易四碼中，有多出[地址鍵打出符號]跟[有候選字時會有嗶聲提示]的功能，請問自建輸入法能加入功能嗎?

**Comment by jrywu** [comment]
請把你的大易碼表轉成 UTF-16LE 編碼，放在 c:\users\[username]\appdata\roaming\DIME\dayi.cin ，DIME 大易就會優先去抓這個碼表，不要用自建輸入法。
