### ISSUE TITLE
Win10 1809 關連字 

### ISSUE THREAD

**Issue by hotsher** [jrywu/DIME#17]
Win10 1809關連字功能無法闗閉
使用
EnableAssociatePhrase 的資料為 0x00000000 (0)，即 0 （0x00000000為十六進位的0）。0表示關閉相關字詞功能，未來如果想要開啟，可雙擊 EnableAssociatePhrase 來編輯「數值資料」，從 0 改為 1即可。
亦無法關閉

請問要如何才能夠關閉?

**Comment by jrywu** [comment]
EnableAssociatePhrase  是 Windows 內建大易的設定跟 DIME 無關。
DIME 的聯想詞設定請按  Ctrl-\ 後，把提示聯想詞勾勾去掉就可以了。
1809 測試過也沒問題。

**Comment by hotsher** [comment]
Thanks!!


在 2019年1月9日 下午12:56:07 Jeremy Wu <notifications@github.com> 寫道:
