### ISSUE TITLE
快打模式下，有些字沒有限制只能用特別碼輸入

### ISSUE THREAD

**Issue by gdfan777** [jrywu/DIME#18]
您好：

發現在「快打模式」下，「式」字用 2 級簡碼輸入時 (1- 1^ 2)，也可以上字，沒有被限制只能打特別碼 (8v 2v)，不像其他特別碼文字，就算打 2 級簡碼也無法上字。與「理」(1- 4^ 0，特別碼 7v 8^) 比較。

**Comment by jrywu** [comment]
Fixed at v1.1.273
