### ISSUE TITLE
打字候選欄的長寬度能縮減嗎？還有打字時的游標總是會離0.1cm！不習慣

### ISSUE THREAD

**Issue by wsxcom** [jrywu/DIME#20]
1.打字候選欄的長寬度能縮減嗎？
2.出字的反應不夠快
3.在工作列能快速切換簡體和繁體
4.官方網址？

**Comment by jrywu** [comment]
1. 請按  ctrl - \ 熱鍵進入設定頁面，把字型變小，長寬就會縮減。
2. DIME 的碼表會全部載入到記憶體中，除非你的記憶體不足，不然不可能更快了。
3. 要符合Windows TSF 工作列的規範不允許 。
4. 就在這裡。
