### ISSUE TITLE
Dime 設定輸出繁體字／簡體字的問題

### ISSUE THREAD

**Issue by internlin** [jrywu/DIME#25]
您好，如題所問。

Dime 設定「輸出繁體字／簡體字」時，仍會出現「繁體字／簡體字」的選字？

例如 Dime 的大易輸入法就有這個狀況。

請問這是 bug 嗎？

**Comment by internlin** [comment]
如附圖，感恩。 Orz

![Dime 的大易設定 bug--01](https://user-images.githubusercontent.com/44114483/76406014-05c8b180-63c4-11ea-94d9-5a10b7feac0d.png)
![Dime 的大易設定 bug--02](https://user-images.githubusercontent.com/44114483/76406107-2a248e00-63c4-11ea-8b6e-37143664f3ea.png)

**Comment by jrywu** [comment]
輸出字元選擇簡體是把常用的繁體字轉成簡體字 (打繁出簡 )。
DIME 用的大易是Windows 內建的大易碼表 (C:\Program Files\Windows NT\TableTextService\TableTextServiceDaYi.txt) 這個碼表包含 Unicode 28000字左右，本來就包含簡體字 。打字出的選項由碼表決定，碼表有什麼就出什麼跟上面設定無關。如果不想看到簡體字，必須把此碼表中的簡體字 剔除。

**Comment by internlin** [comment]
謝謝您，非常感恩您的解答！
