### ISSUE TITLE
Dime 會與 Adobe Acrobat Reader DC 衝突

### ISSUE THREAD

**Issue by internlin** [jrywu/DIME#26]
您好，如題所問。

Dime 會與 Adobe Acrobat Reader DC 衝突，造成 Adobe Acrobat Reader DC 開啟 PDF 後呈現全黑，看不到內容。

在作業系統 Win7、Win10 之下皆有這種狀況，一旦解除安裝DIME，Adobe Acrobat Reader DC 開啟 PDF 就正常。

錯誤如附圖，感恩。 Orz

![Dime 的 bug--20200312](https://user-images.githubusercontent.com/44114483/76481909-ac0cc980-644d-11ea-94b8-02f519c82c46.png)

**Comment by jrywu** [comment]
請修改下列registry 關閉Acrobat reader 保護模式可以解決此問題
[HKEY_CURRENT_USER\SOFTWARE\Adobe\Acrobat Reader\10.0\Privileged]
"bProtectedMode"=dword:00000000

**Comment by internlin** [comment]
謝謝您，非常感恩您的解答！

**Comment by AlCahng** [comment]
從Regedit內修改的方法，在新版的Adobe Acrobat Reader無作用。要在程式內設定才有用。

執行Adobe Acrobat Reader，然後點擊「編輯」→「偏好設定」→「安全性（增強）」
不要勾選「啟動時啟用受保護模式」
