### ISSUE TITLE
請問如何移除用不到的輸入法

### ISSUE THREAD

**Issue by fenky** [jrywu/DIME#28]
我是win 10 安裝DIME之後，有自訂及行列，但我只需要使用大易，而我在控制台裡找不到移除輸入法的選項，請問我該如何做呢？
謝謝
2020-03-21

**Comment by pn568** [comment]
試試在語言喜好設定，然後選中文（台灣），按選項之後應該會見到了

**Comment by welly118** [comment]
成功了，謝謝
