### ISSUE TITLE
組字結果差異小問題

### ISSUE THREAD

**Issue by xjackie** [jrywu/DIME#3]
有些字輸入的結果會不一致，如 '負' 這個字，打完  7-7v 後，不會有待選框出來，但直接按空白鍵還是會出來，但其他只有單一選擇的字，如 任、會、單 ... 等，打完後，即使只有一個字可選，也會有選字窗出來 ?

**Comment by jrywu** [comment]
最新commit 版本已有老刀修正簡碼碼表解決此問題。
請安裝最新版本並到 c:\users\[username]\appdata\roaming\DIME\ 下刪除array*.cin ，新的碼表就會作用。
