### ISSUE TITLE
請問這個輸入法有打繁出簡的功能嗎?

### ISSUE THREAD

**Issue by dasu88** [jrywu/DIME#30]
如title所述，請問這個輸入法有打繁出簡的功能嗎?

**Comment by pn568** [comment]
安裝後, 在可以打字的地方按下: [Ctrl] + [\]
然後有一個窗口彈出來, 在接近底部的地方又一個選項：輸出字元
這裡就可以選繁體還是簡體輸出了

**Comment by dasu88** [comment]
> 安裝後, 在可以打字的地方按下: [ Ctrl ] + [ \ ]
> 然後有一個窗口彈出來, 在接近底部的地方有一個選項：輸出字元
> 這裡就可以選繁體還是簡體輸出了

謝謝回應，這樣的設定是固定式的輸出調整。
如果它能做到像嘸蝦米、對岸的大大甚至更早前的Yahoo奇摩輸入法
直接利用快速鍵切換繁簡輸入，相信會更趨完美
也許可以列入未來開發的功能請願，
無論如何，謝謝提供這個輸入法。
