### ISSUE TITLE
在某些網頁輸入時，「組字錯誤」的位置會跑掉

### ISSUE THREAD

**Issue by internlin** [jrywu/DIME#32]
您好，如題所問。

Dime 在某些網頁輸入時，「組字錯誤」的位置會跑掉。

狀況如附圖，感恩。 Orz
![20200429-組字錯誤訊息位置跑掉舉例--01](https://user-images.githubusercontent.com/44114483/80559265-98beb900-8a0f-11ea-9eb0-cf4d8c7c7cbf.png)

**Comment by jrywu** [comment]
這是 Windows TSF 的 bug 哦，很偶爾的狀況會出現，程式關掉再打開就會恢復正常，目前無解。
