### ISSUE TITLE
組字區變成怪怪的

### ISSUE THREAD

**Issue by internlin** [jrywu/DIME#33]
您好，問題如附圖的紅圈圈處。

因為這個問題確實發生，但很難再現。因此這個畫面是我努力想辦法
用記憶復刻出來，有發生過的人一定會知道我說的是什麼，嗚嗚～

敬請協助處理了，感恩。 Orz
![20200429-組字區變成怪怪的--01v2](https://user-images.githubusercontent.com/44114483/80559361-dc192780-8a0f-11ea-93b9-b58047c6d9ad.png)

**Comment by jrywu** [comment]
這是 Windows TSF 的 bug 哦，很偶爾的狀況會出現，程式關掉再打開就會恢復正常，目前無解。
