### ISSUE TITLE
載入聯想詞表問題

### ISSUE THREAD

**Issue by uccoffee** [jrywu/DIME#34]
我在自訂輸入法內 錯誤地 載入聯想詞表，之後所有聯想詞消失了。
我想請問怎樣修復？ 我已經試過刪除DIME再安裝聯想詞也沒有修復。

也想請問聯想詞表的格式是怎樣的？

**Comment by jrywu** [comment]
DIME 預設抓Windows 內建的大易表中的聯想詞表 (C:\Program Files\Windows NT\TableTextService\TableTextServiceDaYi.txt 中的 [Phrase] 段落。
如果要自定聯想詞在 c:\users\[username]\appdata\Roaming\DIME 目錄(這個目錄存 DIME 的個人設定在重裝的時候不會動 )下有 Phrase.cin 就會被叫用，格式是 .cin 格式但是編碼必須是 UTF-16LE，範例如下:
%chardef begin
一	個
一	點
一	樣
%chardef end
如果是 UTF-8 的 .cin 可以用自建輸入法設定頁面中的"載入聯想詞表" 按鍵載入，輸入法會自動轉碼並放入前述個人設定目錄。此聯想詞表會是所有DIME 輸入法都共用，不限給自建。
