### ISSUE TITLE
行列二級簡碼誤植

### ISSUE THREAD

**Issue by MisterFISHUP** [jrywu/DIME#38]
你好，DIME 行列二級簡碼表使用的 Gontera Yeh 碼表有誤，不小心將 ux 誤植為 wx，導致 DIME 行列二級簡碼 ux 和 wx 有問題。我昨天告知 Gontera Yeh 後，他已更正碼表並上傳至 [GitHub](https://github.com/gontera/array30/tree/master/OpenVanilla)，希望 DIME 行列也能更正^^

**Comment by jrywu** [comment]
Fixed at DIME v1.1.273a
