### ISSUE TITLE
在遊戲英雄聯盟的大廳輸入法正常，但在進入開始對戰遊戲後，遊戲中的聊天視窗無法正常輸入

### ISSUE THREAD

**Issue by algor66** [jrywu/DIME#39]
如題！
DIME輸入法真的很好用，在 Metro APP、 Microsoft Store 都能輸入中文，但我有在玩LOL，偏偏就這遊戲用DIME不能輸入中文，目前很多輸入法在這遊戲也無法正常輸入，當然windows內鍵的輸入法是可以正常輸入，但就是用起來不習慣。

**Comment by jrywu** [comment]
沒有英雄聯盟，無法再現與除錯。
