### ISSUE TITLE
注音輸入法，的標點符號輸入功能

### ISSUE THREAD

**Issue by Cheniyuan** [jrywu/DIME#4]
您好
謝謝開發的注音輸入法造福大家
目前已經讓我們ㄧ群傳統注音的使用者
能夠在新的Windows 10中可以找回以前輸入法的順手度。
不過目前有個問題很困擾著我們，就是全形標點符號的問題。
目前沒有辦法可以輸出全形的標點符號，
如果您未來有改版的時候，希望能增加透過Ctrl + 標點符號的方式
或是其他功能，讓傳統注音的使用者能夠輸入全形的標點符號。

謝謝您的付出。

**Comment by Shiaobin** [comment]
不好意思，把這個一年多以前的 issue 再翻出來。我也覺得這個功能有其必要性，希望能實現，謝謝！

**Comment by jrywu** [comment]
很抱歉! 新功能目前的狀態真的是有心無力。
