### ISSUE TITLE
同音字查詢功能

### ISSUE THREAD

**Issue by ddlee0901** [jrywu/DIME#40]
[轉帖自PIME](https://github.com/EasyIME/PIME/issues/302)
首先謝謝各位做出這麼強大的輸入法框架，適用各種不同的輸入法。
我有一個小小的建議，官方的嘸蝦米輸入法有一個很好用的功能叫同音字查詢。
這樣**如果忘了一個字怎麼寫，只要知道其中一個同音字的字碼，就可以列出同音的所有字**
如此不用轉換輸入法就可以利用注音來找字。
如果可以實做這個功能，可以造福所有拆字型的輸入法！
請考慮考慮！
謝謝！

**Comment by jrywu** [comment]
謝謝建議 ，下次改版會考慮，但近期內應該很難
