### ISSUE TITLE
Can not call the configuration UI on Windows 1909 Build 18363.1379

### ISSUE THREAD

**Issue by wstephen** [jrywu/DIME#42]
Even with the latest v1.1.273b, I cannot call out the Configuation UI from Note.exe using [Ctrl]+[ \ ].  If I repeatedly pressing [Ctrl+ \ ] more than twice. Note.exe collapsed!

Tried pressing the Ctrl+/ without marking on any test processing software, Windows File Explorer refreshed with black screen and came back in 2 seconds without the [繁體]+[中/英] icons to the "right side" of the volume icon on the taskbar.

So, how to invoke DIME's GUI?  Is there any alternative way to do so?

**Comment by jrywu** [comment]
The GUI invoking hot key is [Ctrl]+[\].  Unfortunately, there are no alternative method.   The hotkey only works on win32/64 conventional applications.  It's not working on modern (metro) apps and applications running sandbox, like IE.   The simplest way is to run notepad.exe or windows file explorer.   My computer is running Windows 20H2 and didn't see problem in all versions till the latest 20H2.
