### ISSUE TITLE
大昜無法在Windows搜尋或是自黏便籤等軟體中輸入中文

### ISSUE THREAD

**Issue by snwei727** [jrywu/DIME#43]

**Comment by snwei727** [comment]
注音則可以正常輸入

**Comment by jrywu** [comment]
請明確化什麼 Windows 版本，什麼位置的搜尋，自黏便箋是哪一套軟體?

**Comment by snwei727** [comment]
Windows 10 版本 20H2  19042.928
在Microsoft Store搜尋Microsoft自黏便箋
另外像Windows工作列上的放大鏡按下的搜尋輸入框，也無法正常用大昜輸入中文，試過注音可以
檔案總管右上的搜尋輸入框也是一樣無法用大昜輸入中文

**Comment by jrywu** [comment]
測試過2台  20H2 19042.928 在你說的地方輸入都正常，請確定是不是個別系統的問題或重灌試試

**Comment by snwei727** [comment]
可以了，把DIME移除乾淨及 \AppData\Roaming\DIME 資料匣也刪除後重新安裝就可以了，感謝!
