### ISSUE TITLE
希望字根區的字型大小能調整，感恩！

### ISSUE THREAD

**Issue by internlin** [jrywu/DIME#44]
您好，

目前 dime 的選字區的字型大小是能調整的，這很棒，對老人家來說更是護眼的福音！

但不知日後 dime 是否能提供調整字根區的字型大小的選項呢？

感恩！
![20210511](https://user-images.githubusercontent.com/44114483/117783204-e998fc80-b274-11eb-9aaf-7a45c16acccf.png)

**Comment by jrywu** [comment]
字根區的字型大小是跟著打出來的字型大小。記事本裡 格式-> 字型 ，加大字級，顯示的字變大，字根區就會跟著變大。
