### ISSUE TITLE
4K解析度下選字框過小

### ISSUE THREAD

**Issue by RexMu** [jrywu/DIME#49]
目前微軟自己出的輸入法有針對這部份做最大200%的放大設定
不知DIME有沒有機會加入這個部份的設定
https://imgur.com/undefined

**Comment by RexMu** [comment]
> 目前微軟自己出的輸入法有針對這部份做最大200%的放大設定
> 不知DIME有沒有機會加入這個部份的設定
> https://imgur.com/undefined
實拍畫面
https://imgur.com/SJDKdLv

**Comment by jrywu** [comment]
DIME 預設是12級字，是大部分軟體最常用的字型大小，如果你覺得太小應該是先去調Windows 顯示的字型放大。如果你要DIME 單獨變大，請按 ctrl-\ 把顯示字體加大。
