### ISSUE TITLE
【大易】有無可能提供「有候選字時嗶聲提示」選項

### ISSUE THREAD

**Issue by casinero** [jrywu/DIME#5]
就是 希望在下圖情況時也能可以一聲嗶聲提示，跟錯誤組字時一樣
![image](https://cloud.githubusercontent.com/assets/10470585/24198745/16733732-0f42-11e7-9119-556cf364b63d.png)

DIME大易真的比Win10內建的流暢又貼心許多
感謝大大佛心

**Comment by jrywu** [comment]
已完成

**Comment by casinero** [comment]
感謝大大
