### ISSUE TITLE
關於DIME的"使用者"授權

### ISSUE THREAD

**Issue by chiahuai** [jrywu/DIME#51]
Jeremy，您好，

我是一個行列40輸入法的重度使用者，目前僅能藉由安裝如GCIN或DIME的方式來掛載行列40的方式來進行輸入法的使用，近日因工作的需要，需要使用公司所配發的設備來進行中文的輸入，而同時公司對於非標準軟體的安裝有一定的審查程序，其中一項即是必須取得該軟體的"使用"授權，因此想要冒昧請教您不論DIME的使用是否需要付費，同時是否有什麼方式能取得DIME的使用授權資料（書面文件或email說明等）說明一般個人是可以使用DIME於職場中的設備進行安裝使用。

Best regards,
Kevin

**Comment by jrywu** [comment]
DIME Github 頁面以宣告 BSD 3-clause (2.0) 版權，所有原始檔也都加上BSD 版權宣告。只要符合 BSD 3-clause 原則，授權合法免費使用，如果網路版權頁面還不足，請再連絡我。
