### ISSUE TITLE
DIME 輸入法在Java程式寫的軟上無法使用

### ISSUE THREAD

**Issue by a9231219** [jrywu/DIME#52]
您好

非常感謝您開發的DIME輸入法讓需要使用大易4碼的我能找回如同過以往舊大易輸入的使用體驗
目前有遇到只要是在用Java開發出來的程式或小工具上(ex. jd-gui-windows Java反編譯工具)
就會造成DIME無法輸出中文字只能使用英文
希望能夠修正這個狀況
非常感謝

**Comment by jrywu** [comment]
可以提供Windows 版本，Java 版本或截圖嗎? 初步測試在 x64 Windows 11 的 jd-udi 環境是正常的
