### ISSUE TITLE
倚天注音 不能用

### ISSUE THREAD

**Issue by peter8777555** [jrywu/DIME#53]
Ver : DIME V1.1.285
OS : Windows 7 X64

1.
使用 標準鍵盤 正常使用,
使用 倚天鍵盤 不能打中文,只能打英文.

2.
倚天鍵盤 有  2 種,
倚天 26 鍵鍵盤排列,
倚天 41 鍵鍵盤排列,
我使用 倚天 41 鍵鍵盤排列,有支援嗎 ?

**Comment by jrywu** [comment]
1. 已在 v1.2.325 版修正，請到 Release 頁面下載最新版。
2. DIME 支援的倚天鍵盤是倚天 41 鍵，不支援倚天 26 鍵。

**Comment by peter8777555** [comment]
Ver : DIME V1.2.325
OS : Windows 7 X64

倚天 41 鍵注音

. 對應 ㄒ 這是錯的,應該是 ㄔ
