### ISSUE TITLE
中文模式時[Shift]+英文字輸入問題

### ISSUE THREAD

**Issue by roytam1** [jrywu/DIME#55]
想問一下，能不能有一個選項，在中文模式時以[Shift]+英文字能輸出跟Caps Lock狀態一樣的英文字母?

在XP舊倉頡的時代，中文模式時以[Shift]+英文字能輸出跟Caps Lock狀態一樣的英文字母，但其後的IME框架把這功能取消了(變成跟Caps Lock狀態相反的，可能是因為[Shift]鍵的關係)。

**Comment by jrywu** [comment]
會考慮在下版加入輸入法選項
