### ISSUE TITLE
Shift+Space無法切換全形/半形

### ISSUE THREAD

**Issue by roytam1** [jrywu/DIME#56]
OS: Win10 1809 LTSC x64
在自建輸入法中無法以按Shift+Space來切換全形/半形，但按圖示可以。

**Comment by jrywu** [comment]
請在設定頁面中"全半型輸入模式" 選取 "以 Shift-space 熱鍵切換" ，DIME 預設模式為"半型" ，需改選此選項後才能以 shift-space 切換
