### ISSUE TITLE
選字視窗透明度

### ISSUE THREAD

**Issue by rmmaniac** [jrywu/DIME#57]
我用最後一個版本，非常好用，比windows內建的好用很多
有2個介面的設定想請教，
1:行列輸入的浮動選字視窗，透明度是否可調整不透明或修正，選字視窗下密密麻麻的字影響了選字的清晰度。        
2:選字視窗字型高度的間隔是否可縮小？有很多字型行高非常大，如恩源黑體，把整個選字視窗撐很大。
以上感謝~~

**Comment by jrywu** [comment]
會考慮在下版加入透明度與行距到輸入法選項
