### ISSUE TITLE
大易SHIFT+符號功能失效

### ISSUE THREAD

**Issue by RexMu** [jrywu/DIME#59]
大易輸入法輸入特殊符號時會用到 = 和 SHIFT
先按=啟動符號輸入
再視情況按SHIFT更換符號
例如 6和^
但在1.2.325版之後這個功能會在按下SHIFT時直接切換成英數
無法判斷是按住SHIFT變更輸入內容
改裝回1.1.285就正常了

**Comment by jrywu** [comment]
v1.3.337 版已解結
