### ISSUE TITLE
Windows10更新1703之後，在Line使用DIME輸入法開啟關聯字詞彙Crash

### ISSUE THREAD

**Issue by haimter** [jrywu/DIME#6]
如題，在Windows10更新1703之後，Line上面使用DIME輸入法開啟關聯字詞會讓輸入法整個Crash

**Comment by jrywu** [comment]
剛更新完 1703，在Line 跟其他程式測試都正常，沒發生crash。

可以麻煩提供更詳細的再現步驟跟截圖嗎，謝謝。

Jeremy


________________________________

**Comment by jrywu** [comment]
抱歉，今天用了幾小時，確實有發生程式閃退的情形，而且不只line.

可是目前發生的情況有點隨機，沒有找到可以重現的步驟，沒有辦法修程式。

麻煩您幫忙注意一下，如果有找到可以再現的步驟，再請您來信告知，謝謝 。
Jeremy



________________________________

**Comment by jrywu** [comment]
v1.1.243 應該已經解決這個問題
Download at https://github.com/jrywu/DIME/raw/master/installer/DIME-x8664.zip

**Comment by haimter** [comment]
測試中，舊版Line跟Office五分鐘內會掛，更新後到目前都沒什麼問題了
