### ISSUE TITLE
請問 #60 關閉 是不會實作這個功能嗎 ?

### ISSUE THREAD

**Issue by peter8777555** [jrywu/DIME#62]
請問 :

修正 #61 以shift 鍵切換時，中文/英文 顯示不正確
下載 DIME v1.2.339

您把 #60 關閉 是不會實作這個功能嗎 ?

**Comment by internlin** [comment]
作者的公告，是指說已修正完成喔...

**Comment by peter8777555** [comment]
#60 還沒修正完成喔...

**Comment by internlin** [comment]
您要的那個功能在選項裡有，可以選擇開或關...

**Comment by jrywu** [comment]
目前的小改版僅處理v1.2 的bug，不實作新功能：。標示 enhancement 新功能。的會在下版( v1.3) 加入。

**Comment by peter8777555** [comment]
感谢作者回覆.
