### ISSUE TITLE
DIME 大易輸入法中文模式下無法以九宮格數字鍵輸入數字及-,/ 等符號

### ISSUE THREAD

**Issue by dschuTW** [jrywu/DIME#65]
jrywu SIR 您好：
謝謝您的DIME輸入法，讓大家可以擺脫win10內建難用的大易，近期發現您更新了DIME至1.2版，下載安裝1.2.339後發現在大易中文輸入模式下，鍵盤九宮格數字鍵無法打出數字與"-","/"，需要切回英文模式，不知是否有什麼設定可以回復中文模式下，直接按右邊九宮格數字鍵即可快速輸入半形數字，謝謝您！

**Comment by gontera** [comment]
有問題的部分，應是在於實體鍵盤左邊「標準鍵盤」與右邊「數字鍵盤」的共同字符上面。目前當使用者按下這些字符的按鍵當下，DIME 似乎無法分辨使用者按的是「標準鍵盤」的字符鍵位，或是「數字鍵盤」的字符鍵位。

我也希望 DIME 可以早日修正這個問題，可以大幅增進輸入文字的方便性。

**Comment by jrywu** [comment]
DIME v1.2.339 新增數字鍵盤選項，預設回到輸入數字符號
