### ISSUE TITLE
DIME大易輸入法的問題

### ISSUE THREAD

**Issue by Herry1218** [jrywu/DIME#70]
您好，我下載了最新的DIME1.2.345版本，但發現若按數字鍵盤上的"-"，會出現字根"鄉"，而不是-，所以想請問有辦法可以讓數字鍵盤上的鍵盤選項就只是數字鍵盤，不要出現大易的字根嗎?或者要下載哪個版本來使用才對。謝謝！

**Comment by wzhuang1223** [comment]
大易輸入法的數字鍵也是字根的一部份喔

**Comment by internlin** [comment]
看來是 bug 的樣子，比較老的版本沒有這個問題...？

**Comment by jrywu** [comment]
已修正，請幫忙測試，沒問題再 Release，謝謝
https://github.com/jrywu/DIME/raw/master/installer/DIME-x86armUniversal.zip

**Comment by Herry1218** [comment]
謝謝您，測試後沒有問題了，數字鍵盤上-鍵是-了。
但有另一個問題，回家用筆電時，為什麼在word、PPT、LINE之類的DIME大易都是正常大易的字根；但若在網頁上（不管是chrome、IE）要打字，但變成注音的字根，請問我有哪裡設定錯誤嗎？謝謝

**Comment by jrywu** [comment]
不太能了解注音字根是什麼意思，可以截圖說明嗎?

**Comment by Herry1218** [comment]
![1](https://user-images.githubusercontent.com/126855651/222877409-a25f54a8-6682-472e-a572-85db566f8c32.jpg)
![2](https://user-images.githubusercontent.com/126855651/222877411-bbbd5d10-e34e-4bdd-a465-1f0b828d68ac.jpg)
![3](https://user-images.githubusercontent.com/126855651/222877412-80de0586-066c-4ab1-b707-0e59db278648.jpg)
就是在瀏覽器要輸入，結果是出現注音，無法打大易的字根，但在word line PPT都沒有問題；
但有朋友幫我用，結果現在只能打英文了，不知是那裡衝到了？？謝謝

**Comment by jrywu** [comment]
這是Windows 沒有正常載入輸入法 dll，通常是chrome 關掉重開，或重開機就會好。如果再不行就重裝DIME安裝檔。
