### ISSUE TITLE
內建大易輸入法的字根檔

### ISSUE THREAD

**Issue by OscarLai** [jrywu/DIME#71]
您好
請問內建大易輸入法的字根檔放在什麼目錄下
我想自行調整成習慣的選字順序
或是也可以像自訂輸入法一樣可以用自備的cin檔
謝謝

**Comment by internlin** [comment]
在 AppData\Roaming\DIME 裡喔，您可以試試看

**Comment by jrywu** [comment]
大易比較特別，使用的碼表是Windows 內建的碼表，TableTextServiceDaYi.txt  DIME 會被這個檔案從系統的位置 copy 到 AppData\Roaming\DIME 。但不建議改這個檔案，有客製的需求的可以把 Appdata\Roaming\DIME\Dayiconfig.ini 加入一行 LoadTableMode = 1。再進 DIME 設定-> DIME大易輸入法設定->自建詞庫  頁面按 載入主碼表可以載入標準的 .cin 格式碼表

**Comment by internlin** [comment]
作者您好，順道一問。如果我重整了大易的碼表，您還是建議用自建詞庫的方式來作嗎？這樣不會造成碼表重複，和記憶體空間的重複浪費嗎？

**Comment by jrywu** [comment]
不是自建詞庫，是自建詞庫這個頁面下面載入主碼表的按鍵可以導入一個  .cin 主碼表取代內建主碼表。自建詞庫的功能還是在的，主碼表查不到的會再去查自建詞庫 。
________________________________
